apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  project: default
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.14.4 # renovate: depName=external-dns
      helm:
        releaseName: external-dns
    - repoURL: https://github.com/ponkio-o/argocd-diff-preview-sample.git
      targetRevision: main
      ref: this
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
